import test from "node:test";
import assert from "node:assert/strict";
import { DETECTORS, CAPABILITIES, getDetector } from "../src/detectors/catalog.js";
import { buildIntensityMap, classifyPolarization, cloneDefaultSignal, measureSignal, peakIrradiance } from "../src/detectors/measure.js";

test("catalog contains eight unique requested detectors",()=>{assert.equal(DETECTORS.length,8);assert.equal(new Set(DETECTORS.map(({id})=>id)).size,8);});
test("camera exposes spatial map, beam diameters, and image status",()=>{const result=measureSignal("camera");assert.equal(result.visuals.intensityMap.length,25);assert.ok(result.readouts.some(({id})=>id==="diameter-x"));assert.ok(result.readouts.some(({id})=>id==="image"));});
test("photodetector and PMT are distinct",()=>{assert.deepEqual(getDetector("photodetector").capabilities,[CAPABILITIES.INTENSITY]);assert.deepEqual(getDetector("photomultiplier").capabilities,[CAPABILITIES.LOW_LIGHT]);assert.ok(measureSignal("photomultiplier").readouts.some(({id})=>id==="photon-rate"));});
test("power meter reads incoming power",()=>{const signal=cloneDefaultSignal();signal.powerW=7.5e-3;assert.equal(measureSignal("power-meter",signal).readouts[0].value,7.5e-3);});
test("wavefront detector identifies collimated and diverging beams",()=>{const signal=cloneDefaultSignal();signal.wavefront.divergenceRad=.05e-3;assert.equal(measureSignal("wavefront-detector",signal).readouts.find(({id})=>id==="collimation").value,"Collimated");signal.wavefront.divergenceRad=1.4e-3;assert.equal(measureSignal("wavefront-detector",signal).readouts.find(({id})=>id==="collimation").value,"Diverging");});
test("polarimeter classifies common states",()=>{assert.equal(classifyPolarization([1,1,0,0]).label,"Linear");assert.equal(classifyPolarization([1,0,0,1]).label,"Left circular");assert.equal(classifyPolarization([1,.01,.01,.01]).label,"Unpolarized");});
test("spectrometer returns wavelength, bandwidth, and spectrum",()=>{const result=measureSignal("spectrometer");assert.equal(result.visuals.spectrum.length,49);assert.deepEqual(result.readouts.map(({id})=>id),["wavelength","bandwidth"]);});
test("general detector exposes all properties and pulse timing",()=>{const result=measureSignal("general-detector");const ids=new Set(result.readouts.map(({id})=>id));for(const id of ["peak-intensity","power","spatial-map","diameter-x","image","collimation","polarization","wavelength","repetition-rate","pulse-duration"])assert.ok(ids.has(id),id);assert.equal(result.caveats.length,1);});
test("continuous-wave input marks pulse values unavailable",()=>{const signal=cloneDefaultSignal();signal.pulse.isPulsed=false;const result=measureSignal("general-detector",signal);assert.equal(result.readouts.find(({id})=>id==="repetition-rate").available,false);});
test("measurement helpers are deterministic and reject invalid data",()=>{const signal=cloneDefaultSignal();assert.equal(peakIrradiance(signal),8*signal.powerW/(Math.PI*signal.beam.diameterXM*signal.beam.diameterYM));assert.deepEqual(buildIntensityMap(signal,7,5),buildIntensityMap(signal,7,5));assert.throws(()=>measureSignal("unknown"),/Unknown detector/);signal.powerW=NaN;assert.throws(()=>measureSignal("camera",signal),/powerW/);});
